version: '3'
services:
  nodejs-server:
    build:
      context: ./backend
    ports:
      - '8080:8080'
    container_name: node-api
    volumes:
      - ./backend:/usr/src/app/api
      - /usr/src/app/api/node_modules
  react-ui:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    container_name: react-ui
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app/my-app
      - /usr/src/app/my-app/node_modules
