name: Code Collab Backend

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install deps
        working-directory: ./backend
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Run lint
        working-directory: ./backend
        run: npm run lint
      - name: Run Build
        working-directory: ./backend
        run: npm run build
        env:
          CI: ''
      - name: Remove yarn.lock
        working-directory: ./backend
        run: git rm yarn.lock
      - name: Deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_TOKEN}}
          heroku_app_name: 'code-collab-api'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: backend
