name: Deploy To Heroku

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: Install deps
        working-directory: ./frontend
        run: npm i
      - name: Run lint
        working-directory: ./frontend
        run: npm run lint
      - name: Run Build
        working-directory: ./frontend
        run: npm run build
        env:
          CI: ''
      - name: Deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_TOKEN}}
          heroku_app_name: 'code-collab'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
